/*
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.sme.frsl.FRSLRuntimeModule;
import org.eclipse.sme.frsl.FRSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FRSLIdeSetup extends FRSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FRSLRuntimeModule(), new FRSLIdeModule()));
	}
	
}
