/*******************************************************************************
 * generated by Xtext 2.25.0
 *
 * This code is auto-generated
 * from: org.eclipse.sme.frsl/model/FRSLCS.genmodel
 *
 * Only the copyright statement is editable.
 *******************************************************************************/
package	org.eclipse.sme.frslcs.util;

import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.jdt.annotation.Nullable;
import org.eclipse.ocl.pivot.Element;
import org.eclipse.ocl.xtext.base.cs2as.CS2ASConversion;
import org.eclipse.ocl.xtext.oclinecore.cs2as.OCLinEcoreCSLeft2RightVisitor;

/**
 * An AbstractFrslCSLeft2RightVisitor provides a default implementation for each
 * visitXxx method that delegates to the visitYyy method of the first
 * super class, (or transitively its first super class first super class
 * until a non-interface super-class is found). In the absence of any
 * suitable first super class, the method delegates to visiting().
 */
public abstract class AbstractFrslCSLeft2RightVisitor
	extends OCLinEcoreCSLeft2RightVisitor
	implements FRSLCSVisitor<Element>
{
	/**
	 * Initializes me with an initial value for my result.
	 *
	 * @param context my initial result value
	 */
	protected AbstractFrslCSLeft2RightVisitor(@NonNull CS2ASConversion context) {
		super(context);
	}

	@Override
	public @Nullable Element visitActStepCS(org.eclipse.sme.frslcs.@NonNull ActStepCS csElement) {
		return visitStepCS(csElement);
	}

	@Override
	public @Nullable Element visitActionCS(org.eclipse.sme.frslcs.@NonNull ActionCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitActorActionCS(org.eclipse.sme.frslcs.@NonNull ActorActionCS csElement) {
		return visitActionCS(csElement);
	}

	@Override
	public @Nullable Element visitActorCS(org.eclipse.sme.frslcs.@NonNull ActorCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitAltFlowCS(org.eclipse.sme.frslcs.@NonNull AltFlowCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitAssocEndCS(org.eclipse.sme.frslcs.@NonNull AssocEndCS csElement) {
		return visitReferenceCS(csElement);
	}

	@Override
	public @Nullable Element visitAssociationCS(org.eclipse.sme.frslcs.@NonNull AssociationCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitConstraintCS(org.eclipse.sme.frslcs.@NonNull ConstraintCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitExtendCS(org.eclipse.sme.frslcs.@NonNull ExtendCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitExtensionPointCS(org.eclipse.sme.frslcs.@NonNull ExtensionPointCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitFrslModelCS(org.eclipse.sme.frslcs.@NonNull FrslModelCS csElement) {
		return visitRootCS(csElement);
	}

	@Override
	public @Nullable Element visitObjVarCS(org.eclipse.sme.frslcs.@NonNull ObjVarCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitRejoinStepCS(org.eclipse.sme.frslcs.@NonNull RejoinStepCS csElement) {
		return visitStepCS(csElement);
	}

	@Override
	public @Nullable Element visitSnapshotPatternCS(org.eclipse.sme.frslcs.@NonNull SnapshotPatternCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitStepCS(org.eclipse.sme.frslcs.@NonNull StepCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitSystemActionCS(org.eclipse.sme.frslcs.@NonNull SystemActionCS csElement) {
		return visitActionCS(csElement);
	}

	@Override
	public @Nullable Element visitUCStepCS(org.eclipse.sme.frslcs.@NonNull UCStepCS csElement) {
		return visitStepCS(csElement);
	}

	@Override
	public @Nullable Element visitUsecaseCS(org.eclipse.sme.frslcs.@NonNull UsecaseCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitUsecasePostconditionCS(org.eclipse.sme.frslcs.@NonNull UsecasePostconditionCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitUsecasePreconditionCS(org.eclipse.sme.frslcs.@NonNull UsecasePreconditionCS csElement) {
		return visitModelElementCS(csElement);
	}

	@Override
	public @Nullable Element visitVarLinkCS(org.eclipse.sme.frslcs.@NonNull VarLinkCS csElement) {
		return visitModelElementCS(csElement);
	}
}
