/*******************************************************************************
 * generated by Xtext 2.25.0
 *
 * This code is auto-generated
 * from: org.eclipse.sme.frsl/model/FRSLCS.genmodel
 *
 * Only the copyright statement is editable.
 *******************************************************************************/
package	org.eclipse.sme.frslcs.util;


/*
 * An AbstractFRSLCSVisitor provides a default implementation of the visitor framework
 * but n implementations of the visitXXX methods..
 */
public abstract class AbstractFRSLCSVisitor<R, C>
	extends org.eclipse.ocl.xtext.oclinecorecs.util.AbstractOCLinEcoreCSVisitor<R, C>
	implements FRSLCSVisitor<R>
{
	/**
	 * Initializes me with an initial value for my result.
	 *
	 * @param context my initial result value
	 */
	protected AbstractFRSLCSVisitor(C context) {
		super(context);
	}
}
