/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frslcs;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor Action CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.sme.frslcs.FrslCSPackage#getActorActionCS()
 * @model
 * @generated
 */
public interface ActorActionCS extends ActionCS
{
} // ActorActionCS
