/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frslcs;

import org.eclipse.ocl.xtext.basecs.ReferenceCS;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assoc End CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.sme.frslcs.FrslCSPackage#getAssocEndCS()
 * @model
 * @generated
 */
public interface AssocEndCS extends ReferenceCS
{
} // AssocEndCS
