/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extension Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sme.frsl.ExtensionPoint#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.ExtensionPoint#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.ExtensionPoint#getLocation <em>Location</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.ExtensionPoint#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.ExtensionPoint#getExtend <em>Extend</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getExtensionPoint()
 * @model
 * @generated
 */
public interface ExtensionPoint extends EObject {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getExtensionPoint_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.ExtensionPoint#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getExtensionPoint_Description()
	 * @model
	 * @generated
	 */
	String getDescription();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.ExtensionPoint#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
	void setDescription(String value);

	/**
	 * Returns the value of the '<em><b>Location</b></em>' reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.Step}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Location</em>' reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getExtensionPoint_Location()
	 * @model
	 * @generated
	 */
	EList<Step> getLocation();

	/**
	 * Returns the value of the '<em><b>Condition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Condition</em>' containment reference.
	 * @see #setCondition(SnapshotPattern)
	 * @see org.eclipse.sme.frsl.FrslPackage#getExtensionPoint_Condition()
	 * @model containment="true"
	 * @generated
	 */
	SnapshotPattern getCondition();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.ExtensionPoint#getCondition <em>Condition</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Condition</em>' containment reference.
	 * @see #getCondition()
	 * @generated
	 */
	void setCondition(SnapshotPattern value);

	/**
	 * Returns the value of the '<em><b>Extend</b></em>' reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.Extend}.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.Extend#getExtPoint <em>Ext Point</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Extend</em>' reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getExtensionPoint_Extend()
	 * @see org.eclipse.sme.frsl.Extend#getExtPoint
	 * @model opposite="extPoint"
	 * @generated
	 */
	EList<Extend> getExtend();

} // ExtensionPoint
