/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.eclipse.sme.frsl.FrslPackage
 * @generated
 */
public interface FrslFactory extends EFactory {
	/**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	FrslFactory eINSTANCE = org.eclipse.sme.frsl.impl.FrslFactoryImpl.init();

	/**
	 * Returns a new object of class '<em>Model</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Model</em>'.
	 * @generated
	 */
	FrslModel createFrslModel();

	/**
	 * Returns a new object of class '<em>Usecase</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Usecase</em>'.
	 * @generated
	 */
	Usecase createUsecase();

	/**
	 * Returns a new object of class '<em>Usecase Precondition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Usecase Precondition</em>'.
	 * @generated
	 */
	UsecasePrecondition createUsecasePrecondition();

	/**
	 * Returns a new object of class '<em>Usecase Postcondition</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Usecase Postcondition</em>'.
	 * @generated
	 */
	UsecasePostcondition createUsecasePostcondition();

	/**
	 * Returns a new object of class '<em>Step</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Step</em>'.
	 * @generated
	 */
	Step createStep();

	/**
	 * Returns a new object of class '<em>Include</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Include</em>'.
	 * @generated
	 */
	Include createInclude();

	/**
	 * Returns a new object of class '<em>Extend</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Extend</em>'.
	 * @generated
	 */
	Extend createExtend();

	/**
	 * Returns a new object of class '<em>Extension Point</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Extension Point</em>'.
	 * @generated
	 */
	ExtensionPoint createExtensionPoint();

	/**
	 * Returns a new object of class '<em>Alt Flow</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Alt Flow</em>'.
	 * @generated
	 */
	AltFlow createAltFlow();

	/**
	 * Returns a new object of class '<em>Snapshot Pattern</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Snapshot Pattern</em>'.
	 * @generated
	 */
	SnapshotPattern createSnapshotPattern();

	/**
	 * Returns a new object of class '<em>Obj Var</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Obj Var</em>'.
	 * @generated
	 */
	ObjVar createObjVar();

	/**
	 * Returns a new object of class '<em>Var Link</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Var Link</em>'.
	 * @generated
	 */
	VarLink createVarLink();

	/**
	 * Returns a new object of class '<em>Actor</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Actor</em>'.
	 * @generated
	 */
	Actor createActor();

	/**
	 * Returns a new object of class '<em>Action</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Action</em>'.
	 * @generated
	 */
	Action createAction();

	/**
	 * Returns a new object of class '<em>Actor Action</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Actor Action</em>'.
	 * @generated
	 */
	ActorAction createActorAction();

	/**
	 * Returns a new object of class '<em>System Action</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>System Action</em>'.
	 * @generated
	 */
	SystemAction createSystemAction();

	/**
	 * Returns a new object of class '<em>Rejoin Step</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Rejoin Step</em>'.
	 * @generated
	 */
	RejoinStep createRejoinStep();

	/**
	 * Returns a new object of class '<em>UC Step</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>UC Step</em>'.
	 * @generated
	 */
	UCStep createUCStep();

	/**
	 * Returns a new object of class '<em>Act Step</em>'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return a new object of class '<em>Act Step</em>'.
	 * @generated
	 */
	ActStep createActStep();

	/**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
	FrslPackage getFrslPackage();

} //FrslFactory
