/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.ocl.pivot.PivotPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.sme.frsl.FrslFactory
 * @model kind="package"
 * @generated
 */
public interface FrslPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "frsl";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.xtext.org/sme/FRSL";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "frsl";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	FrslPackage eINSTANCE = org.eclipse.sme.frsl.impl.FrslPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.FrslModelImpl <em>Model</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.FrslModelImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getFrslModel()
	 * @generated
	 */
	int FRSL_MODEL = 0;

	/**
	 * The feature id for the '<em><b>Annotating Comments</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__ANNOTATING_COMMENTS = 1; //PivotPackage.MODEL__ANNOTATING_COMMENTS;

	/**
	 * The feature id for the '<em><b>Owned Annotations</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__OWNED_ANNOTATIONS = 2; //PivotPackage.MODEL__OWNED_ANNOTATIONS;

	/**
	 * The feature id for the '<em><b>Owned Comments</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__OWNED_COMMENTS = 3; //PivotPackage.MODEL__OWNED_COMMENTS;

	/**
	 * The feature id for the '<em><b>Owned Extensions</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__OWNED_EXTENSIONS = 4; //PivotPackage.MODEL__OWNED_EXTENSIONS;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__NAME = 5; //PivotPackage.MODEL__NAME;

	/**
	 * The feature id for the '<em><b>Owned Constraints</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__OWNED_CONSTRAINTS = 6; //PivotPackage.MODEL__OWNED_CONSTRAINTS;

	/**
	 * The feature id for the '<em><b>External URI</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__EXTERNAL_URI = 7; //PivotPackage.MODEL__EXTERNAL_URI;

	/**
	 * The feature id for the '<em><b>Owned Imports</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__OWNED_IMPORTS = 8; //PivotPackage.MODEL__OWNED_IMPORTS;

	/**
	 * The feature id for the '<em><b>Owned Packages</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__OWNED_PACKAGES = 9; //PivotPackage.MODEL__OWNED_PACKAGES;

	/**
	 * The feature id for the '<em><b>Xmiid Version</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__XMIID_VERSION = 0; //PivotPackage.MODEL__XMIID_VERSION;
	
	int PivotPackage_MODEL_FEATURE_COUNT = 10;

	/**
	 * The feature id for the '<em><b>Actor</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__ACTOR = PivotPackage_MODEL_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Usecase</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__USECASE = PivotPackage_MODEL_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Uc Extend</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL__UC_EXTEND = PivotPackage_MODEL_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Model</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FRSL_MODEL_FEATURE_COUNT = PivotPackage_MODEL_FEATURE_COUNT + 3;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.UsecaseImpl <em>Usecase</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.UsecaseImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUsecase()
	 * @generated
	 */
	int USECASE = 1;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Primary Actor</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__PRIMARY_ACTOR = 2;

	/**
	 * The feature id for the '<em><b>Secondary Actor</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__SECONDARY_ACTOR = 3;

	/**
	 * The feature id for the '<em><b>Precondition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__PRECONDITION = 4;

	/**
	 * The feature id for the '<em><b>Postcondition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__POSTCONDITION = 5;

	/**
	 * The feature id for the '<em><b>First Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__FIRST_STEP = 6;

	/**
	 * The feature id for the '<em><b>Ext Point</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__EXT_POINT = 7;

	/**
	 * The feature id for the '<em><b>Include</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE__INCLUDE = 8;

	/**
	 * The number of structural features of the '<em>Usecase</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_FEATURE_COUNT = 9;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.UsecasePreconditionImpl <em>Usecase Precondition</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.UsecasePreconditionImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUsecasePrecondition()
	 * @generated
	 */
	int USECASE_PRECONDITION = 2;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_PRECONDITION__DESCRIPTION = 0;

	/**
	 * The feature id for the '<em><b>Snapshot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_PRECONDITION__SNAPSHOT = 1;

	/**
	 * The number of structural features of the '<em>Usecase Precondition</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_PRECONDITION_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.UsecasePostconditionImpl <em>Usecase Postcondition</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.UsecasePostconditionImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUsecasePostcondition()
	 * @generated
	 */
	int USECASE_POSTCONDITION = 3;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_POSTCONDITION__DESCRIPTION = 0;

	/**
	 * The feature id for the '<em><b>Snapshot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_POSTCONDITION__SNAPSHOT = 1;

	/**
	 * The number of structural features of the '<em>Usecase Postcondition</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USECASE_POSTCONDITION_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.StepImpl <em>Step</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.StepImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getStep()
	 * @generated
	 */
	int STEP = 4;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Pre Step</b></em>' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP__PRE_STEP = 2;

	/**
	 * The feature id for the '<em><b>Next Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP__NEXT_STEP = 3;

	/**
	 * The feature id for the '<em><b>Alt Flow</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP__ALT_FLOW = 4;

	/**
	 * The feature id for the '<em><b>Rejoin From</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP__REJOIN_FROM = 5;

	/**
	 * The number of structural features of the '<em>Step</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STEP_FEATURE_COUNT = 6;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.IncludeImpl <em>Include</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.IncludeImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getInclude()
	 * @generated
	 */
	int INCLUDE = 5;

	/**
	 * The feature id for the '<em><b>Including UC</b></em>' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INCLUDE__INCLUDING_UC = 0;

	/**
	 * The feature id for the '<em><b>Addition</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INCLUDE__ADDITION = 1;

	/**
	 * The number of structural features of the '<em>Include</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INCLUDE_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ExtendImpl <em>Extend</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ExtendImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getExtend()
	 * @generated
	 */
	int EXTEND = 6;

	/**
	 * The feature id for the '<em><b>Extended UC</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTEND__EXTENDED_UC = 0;

	/**
	 * The feature id for the '<em><b>Extension</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTEND__EXTENSION = 1;

	/**
	 * The feature id for the '<em><b>Ext Point</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTEND__EXT_POINT = 2;

	/**
	 * The number of structural features of the '<em>Extend</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTEND_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ExtensionPointImpl <em>Extension Point</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ExtensionPointImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getExtensionPoint()
	 * @generated
	 */
	int EXTENSION_POINT = 7;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTENSION_POINT__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTENSION_POINT__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Location</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTENSION_POINT__LOCATION = 2;

	/**
	 * The feature id for the '<em><b>Condition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTENSION_POINT__CONDITION = 3;

	/**
	 * The feature id for the '<em><b>Extend</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTENSION_POINT__EXTEND = 4;

	/**
	 * The number of structural features of the '<em>Extension Point</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXTENSION_POINT_FEATURE_COUNT = 5;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.AltFlowImpl <em>Alt Flow</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.AltFlowImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getAltFlow()
	 * @generated
	 */
	int ALT_FLOW = 8;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ALT_FLOW__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ALT_FLOW__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Condition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ALT_FLOW__CONDITION = 2;

	/**
	 * The feature id for the '<em><b>Base Step</b></em>' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ALT_FLOW__BASE_STEP = 3;

	/**
	 * The feature id for the '<em><b>Alt Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ALT_FLOW__ALT_STEP = 4;

	/**
	 * The number of structural features of the '<em>Alt Flow</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ALT_FLOW_FEATURE_COUNT = 5;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.SnapshotPatternImpl <em>Snapshot Pattern</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.SnapshotPatternImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getSnapshotPattern()
	 * @generated
	 */
	int SNAPSHOT_PATTERN = 9;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SNAPSHOT_PATTERN__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SNAPSHOT_PATTERN__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Object</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SNAPSHOT_PATTERN__OBJECT = 2;

	/**
	 * The feature id for the '<em><b>Link</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SNAPSHOT_PATTERN__LINK = 3;

	/**
	 * The feature id for the '<em><b>Constraint</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SNAPSHOT_PATTERN__CONSTRAINT = 4;

	/**
	 * The number of structural features of the '<em>Snapshot Pattern</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SNAPSHOT_PATTERN_FEATURE_COUNT = 5;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ObjVarImpl <em>Obj Var</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ObjVarImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getObjVar()
	 * @generated
	 */
	int OBJ_VAR = 10;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OBJ_VAR__NAME = 0;

	/**
	 * The feature id for the '<em><b>Type</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OBJ_VAR__TYPE = 1;

	/**
	 * The feature id for the '<em><b>Is Matched</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OBJ_VAR__IS_MATCHED = 2;

	/**
	 * The number of structural features of the '<em>Obj Var</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OBJ_VAR_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.VarLinkImpl <em>Var Link</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.VarLinkImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getVarLink()
	 * @generated
	 */
	int VAR_LINK = 11;

	/**
	 * The feature id for the '<em><b>Obj Var</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VAR_LINK__OBJ_VAR = 0;

	/**
	 * The feature id for the '<em><b>Assoc</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VAR_LINK__ASSOC = 1;

	/**
	 * The feature id for the '<em><b>Is Neg</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VAR_LINK__IS_NEG = 2;

	/**
	 * The number of structural features of the '<em>Var Link</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VAR_LINK_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ActorImpl <em>Actor</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ActorImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getActor()
	 * @generated
	 */
	int ACTOR = 12;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR__DESCRIPTION = 1;

	/**
	 * The number of structural features of the '<em>Actor</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ActionImpl <em>Action</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ActionImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getAction()
	 * @generated
	 */
	int ACTION = 13;

	/**
	 * The feature id for the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTION__TYPE = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTION__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Actor</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTION__ACTOR = 2;

	/**
	 * The feature id for the '<em><b>Obj Vars</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTION__OBJ_VARS = 3;

	/**
	 * The number of structural features of the '<em>Action</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTION_FEATURE_COUNT = 4;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ActorActionImpl <em>Actor Action</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ActorActionImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getActorAction()
	 * @generated
	 */
	int ACTOR_ACTION = 14;

	/**
	 * The feature id for the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR_ACTION__TYPE = ACTION__TYPE;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR_ACTION__DESCRIPTION = ACTION__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Actor</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR_ACTION__ACTOR = ACTION__ACTOR;

	/**
	 * The feature id for the '<em><b>Obj Vars</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR_ACTION__OBJ_VARS = ACTION__OBJ_VARS;

	/**
	 * The number of structural features of the '<em>Actor Action</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACTOR_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.SystemActionImpl <em>System Action</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.SystemActionImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getSystemAction()
	 * @generated
	 */
	int SYSTEM_ACTION = 15;

	/**
	 * The feature id for the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SYSTEM_ACTION__TYPE = ACTION__TYPE;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SYSTEM_ACTION__DESCRIPTION = ACTION__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Actor</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SYSTEM_ACTION__ACTOR = ACTION__ACTOR;

	/**
	 * The feature id for the '<em><b>Obj Vars</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SYSTEM_ACTION__OBJ_VARS = ACTION__OBJ_VARS;

	/**
	 * The number of structural features of the '<em>System Action</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SYSTEM_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.RejoinStepImpl <em>Rejoin Step</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.RejoinStepImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getRejoinStep()
	 * @generated
	 */
	int REJOIN_STEP = 16;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__NAME = STEP__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__DESCRIPTION = STEP__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Pre Step</b></em>' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__PRE_STEP = STEP__PRE_STEP;

	/**
	 * The feature id for the '<em><b>Next Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__NEXT_STEP = STEP__NEXT_STEP;

	/**
	 * The feature id for the '<em><b>Alt Flow</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__ALT_FLOW = STEP__ALT_FLOW;

	/**
	 * The feature id for the '<em><b>Rejoin From</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__REJOIN_FROM = STEP__REJOIN_FROM;

	/**
	 * The feature id for the '<em><b>Rejoin To</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__REJOIN_TO = STEP_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Condition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP__CONDITION = STEP_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Rejoin Step</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REJOIN_STEP_FEATURE_COUNT = STEP_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.UCStepImpl <em>UC Step</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.UCStepImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUCStep()
	 * @generated
	 */
	int UC_STEP = 17;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__NAME = STEP__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__DESCRIPTION = STEP__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Pre Step</b></em>' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__PRE_STEP = STEP__PRE_STEP;

	/**
	 * The feature id for the '<em><b>Next Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__NEXT_STEP = STEP__NEXT_STEP;

	/**
	 * The feature id for the '<em><b>Alt Flow</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__ALT_FLOW = STEP__ALT_FLOW;

	/**
	 * The feature id for the '<em><b>Rejoin From</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__REJOIN_FROM = STEP__REJOIN_FROM;

	/**
	 * The feature id for the '<em><b>Included UC</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP__INCLUDED_UC = STEP_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>UC Step</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int UC_STEP_FEATURE_COUNT = STEP_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.eclipse.sme.frsl.impl.ActStepImpl <em>Act Step</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.sme.frsl.impl.ActStepImpl
	 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getActStep()
	 * @generated
	 */
	int ACT_STEP = 18;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__NAME = STEP__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__DESCRIPTION = STEP__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Pre Step</b></em>' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__PRE_STEP = STEP__PRE_STEP;

	/**
	 * The feature id for the '<em><b>Next Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__NEXT_STEP = STEP__NEXT_STEP;

	/**
	 * The feature id for the '<em><b>Alt Flow</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__ALT_FLOW = STEP__ALT_FLOW;

	/**
	 * The feature id for the '<em><b>Rejoin From</b></em>' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__REJOIN_FROM = STEP__REJOIN_FROM;

	/**
	 * The feature id for the '<em><b>Pre Snapshot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__PRE_SNAPSHOT = STEP_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Post Snapshot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__POST_SNAPSHOT = STEP_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Action</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__ACTION = STEP_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Is Actor Step</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP__IS_ACTOR_STEP = STEP_FEATURE_COUNT + 3;

	/**
	 * The number of structural features of the '<em>Act Step</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ACT_STEP_FEATURE_COUNT = STEP_FEATURE_COUNT + 4;

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.FrslModel <em>Model</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Model</em>'.
	 * @see org.eclipse.sme.frsl.FrslModel
	 * @generated
	 */
	EClass getFrslModel();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.FrslModel#getActor <em>Actor</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Actor</em>'.
	 * @see org.eclipse.sme.frsl.FrslModel#getActor()
	 * @see #getFrslModel()
	 * @generated
	 */
	EReference getFrslModel_Actor();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.FrslModel#getUsecase <em>Usecase</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Usecase</em>'.
	 * @see org.eclipse.sme.frsl.FrslModel#getUsecase()
	 * @see #getFrslModel()
	 * @generated
	 */
	EReference getFrslModel_Usecase();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.FrslModel#getUcExtend <em>Uc Extend</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Uc Extend</em>'.
	 * @see org.eclipse.sme.frsl.FrslModel#getUcExtend()
	 * @see #getFrslModel()
	 * @generated
	 */
	EReference getFrslModel_UcExtend();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.Usecase <em>Usecase</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Usecase</em>'.
	 * @see org.eclipse.sme.frsl.Usecase
	 * @generated
	 */
	EClass getUsecase();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Usecase#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getName()
	 * @see #getUsecase()
	 * @generated
	 */
	EAttribute getUsecase_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Usecase#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getDescription()
	 * @see #getUsecase()
	 * @generated
	 */
	EAttribute getUsecase_Description();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.Usecase#getPrimaryActor <em>Primary Actor</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Primary Actor</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getPrimaryActor()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_PrimaryActor();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.Usecase#getSecondaryActor <em>Secondary Actor</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Secondary Actor</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getSecondaryActor()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_SecondaryActor();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.Usecase#getPrecondition <em>Precondition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Precondition</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getPrecondition()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_Precondition();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.Usecase#getPostcondition <em>Postcondition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Postcondition</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getPostcondition()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_Postcondition();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.Usecase#getFirstStep <em>First Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>First Step</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getFirstStep()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_FirstStep();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.Usecase#getExtPoint <em>Ext Point</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Ext Point</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getExtPoint()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_ExtPoint();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.Usecase#getInclude <em>Include</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Include</em>'.
	 * @see org.eclipse.sme.frsl.Usecase#getInclude()
	 * @see #getUsecase()
	 * @generated
	 */
	EReference getUsecase_Include();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.UsecasePrecondition <em>Usecase Precondition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Usecase Precondition</em>'.
	 * @see org.eclipse.sme.frsl.UsecasePrecondition
	 * @generated
	 */
	EClass getUsecasePrecondition();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.UsecasePrecondition#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.UsecasePrecondition#getDescription()
	 * @see #getUsecasePrecondition()
	 * @generated
	 */
	EAttribute getUsecasePrecondition_Description();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.UsecasePrecondition#getSnapshot <em>Snapshot</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Snapshot</em>'.
	 * @see org.eclipse.sme.frsl.UsecasePrecondition#getSnapshot()
	 * @see #getUsecasePrecondition()
	 * @generated
	 */
	EReference getUsecasePrecondition_Snapshot();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.UsecasePostcondition <em>Usecase Postcondition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Usecase Postcondition</em>'.
	 * @see org.eclipse.sme.frsl.UsecasePostcondition
	 * @generated
	 */
	EClass getUsecasePostcondition();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.UsecasePostcondition#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.UsecasePostcondition#getDescription()
	 * @see #getUsecasePostcondition()
	 * @generated
	 */
	EAttribute getUsecasePostcondition_Description();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.UsecasePostcondition#getSnapshot <em>Snapshot</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Snapshot</em>'.
	 * @see org.eclipse.sme.frsl.UsecasePostcondition#getSnapshot()
	 * @see #getUsecasePostcondition()
	 * @generated
	 */
	EReference getUsecasePostcondition_Snapshot();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.Step <em>Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Step</em>'.
	 * @see org.eclipse.sme.frsl.Step
	 * @generated
	 */
	EClass getStep();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Step#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.Step#getName()
	 * @see #getStep()
	 * @generated
	 */
	EAttribute getStep_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Step#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.Step#getDescription()
	 * @see #getStep()
	 * @generated
	 */
	EAttribute getStep_Description();

	/**
	 * Returns the meta object for the container reference '{@link org.eclipse.sme.frsl.Step#getPreStep <em>Pre Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the container reference '<em>Pre Step</em>'.
	 * @see org.eclipse.sme.frsl.Step#getPreStep()
	 * @see #getStep()
	 * @generated
	 */
	EReference getStep_PreStep();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.Step#getNextStep <em>Next Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Next Step</em>'.
	 * @see org.eclipse.sme.frsl.Step#getNextStep()
	 * @see #getStep()
	 * @generated
	 */
	EReference getStep_NextStep();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.Step#getAltFlow <em>Alt Flow</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Alt Flow</em>'.
	 * @see org.eclipse.sme.frsl.Step#getAltFlow()
	 * @see #getStep()
	 * @generated
	 */
	EReference getStep_AltFlow();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.Step#getRejoinFrom <em>Rejoin From</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Rejoin From</em>'.
	 * @see org.eclipse.sme.frsl.Step#getRejoinFrom()
	 * @see #getStep()
	 * @generated
	 */
	EReference getStep_RejoinFrom();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.Include <em>Include</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Include</em>'.
	 * @see org.eclipse.sme.frsl.Include
	 * @generated
	 */
	EClass getInclude();

	/**
	 * Returns the meta object for the container reference '{@link org.eclipse.sme.frsl.Include#getIncludingUC <em>Including UC</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the container reference '<em>Including UC</em>'.
	 * @see org.eclipse.sme.frsl.Include#getIncludingUC()
	 * @see #getInclude()
	 * @generated
	 */
	EReference getInclude_IncludingUC();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.Include#getAddition <em>Addition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Addition</em>'.
	 * @see org.eclipse.sme.frsl.Include#getAddition()
	 * @see #getInclude()
	 * @generated
	 */
	EReference getInclude_Addition();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.Extend <em>Extend</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Extend</em>'.
	 * @see org.eclipse.sme.frsl.Extend
	 * @generated
	 */
	EClass getExtend();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.Extend#getExtendedUC <em>Extended UC</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Extended UC</em>'.
	 * @see org.eclipse.sme.frsl.Extend#getExtendedUC()
	 * @see #getExtend()
	 * @generated
	 */
	EReference getExtend_ExtendedUC();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.Extend#getExtension <em>Extension</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Extension</em>'.
	 * @see org.eclipse.sme.frsl.Extend#getExtension()
	 * @see #getExtend()
	 * @generated
	 */
	EReference getExtend_Extension();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.Extend#getExtPoint <em>Ext Point</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Ext Point</em>'.
	 * @see org.eclipse.sme.frsl.Extend#getExtPoint()
	 * @see #getExtend()
	 * @generated
	 */
	EReference getExtend_ExtPoint();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.ExtensionPoint <em>Extension Point</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Extension Point</em>'.
	 * @see org.eclipse.sme.frsl.ExtensionPoint
	 * @generated
	 */
	EClass getExtensionPoint();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.ExtensionPoint#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.ExtensionPoint#getName()
	 * @see #getExtensionPoint()
	 * @generated
	 */
	EAttribute getExtensionPoint_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.ExtensionPoint#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.ExtensionPoint#getDescription()
	 * @see #getExtensionPoint()
	 * @generated
	 */
	EAttribute getExtensionPoint_Description();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.ExtensionPoint#getLocation <em>Location</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Location</em>'.
	 * @see org.eclipse.sme.frsl.ExtensionPoint#getLocation()
	 * @see #getExtensionPoint()
	 * @generated
	 */
	EReference getExtensionPoint_Location();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.ExtensionPoint#getCondition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Condition</em>'.
	 * @see org.eclipse.sme.frsl.ExtensionPoint#getCondition()
	 * @see #getExtensionPoint()
	 * @generated
	 */
	EReference getExtensionPoint_Condition();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.ExtensionPoint#getExtend <em>Extend</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Extend</em>'.
	 * @see org.eclipse.sme.frsl.ExtensionPoint#getExtend()
	 * @see #getExtensionPoint()
	 * @generated
	 */
	EReference getExtensionPoint_Extend();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.AltFlow <em>Alt Flow</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Alt Flow</em>'.
	 * @see org.eclipse.sme.frsl.AltFlow
	 * @generated
	 */
	EClass getAltFlow();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.AltFlow#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.AltFlow#getName()
	 * @see #getAltFlow()
	 * @generated
	 */
	EAttribute getAltFlow_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.AltFlow#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.AltFlow#getDescription()
	 * @see #getAltFlow()
	 * @generated
	 */
	EAttribute getAltFlow_Description();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.AltFlow#getCondition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Condition</em>'.
	 * @see org.eclipse.sme.frsl.AltFlow#getCondition()
	 * @see #getAltFlow()
	 * @generated
	 */
	EReference getAltFlow_Condition();

	/**
	 * Returns the meta object for the container reference '{@link org.eclipse.sme.frsl.AltFlow#getBaseStep <em>Base Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the container reference '<em>Base Step</em>'.
	 * @see org.eclipse.sme.frsl.AltFlow#getBaseStep()
	 * @see #getAltFlow()
	 * @generated
	 */
	EReference getAltFlow_BaseStep();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.AltFlow#getAltStep <em>Alt Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Alt Step</em>'.
	 * @see org.eclipse.sme.frsl.AltFlow#getAltStep()
	 * @see #getAltFlow()
	 * @generated
	 */
	EReference getAltFlow_AltStep();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.SnapshotPattern <em>Snapshot Pattern</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Snapshot Pattern</em>'.
	 * @see org.eclipse.sme.frsl.SnapshotPattern
	 * @generated
	 */
	EClass getSnapshotPattern();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.SnapshotPattern#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.SnapshotPattern#getName()
	 * @see #getSnapshotPattern()
	 * @generated
	 */
	EAttribute getSnapshotPattern_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.SnapshotPattern#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.SnapshotPattern#getDescription()
	 * @see #getSnapshotPattern()
	 * @generated
	 */
	EAttribute getSnapshotPattern_Description();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.SnapshotPattern#getObject <em>Object</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Object</em>'.
	 * @see org.eclipse.sme.frsl.SnapshotPattern#getObject()
	 * @see #getSnapshotPattern()
	 * @generated
	 */
	EReference getSnapshotPattern_Object();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.SnapshotPattern#getLink <em>Link</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Link</em>'.
	 * @see org.eclipse.sme.frsl.SnapshotPattern#getLink()
	 * @see #getSnapshotPattern()
	 * @generated
	 */
	EReference getSnapshotPattern_Link();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.SnapshotPattern#getConstraint <em>Constraint</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Constraint</em>'.
	 * @see org.eclipse.sme.frsl.SnapshotPattern#getConstraint()
	 * @see #getSnapshotPattern()
	 * @generated
	 */
	EReference getSnapshotPattern_Constraint();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.ObjVar <em>Obj Var</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Obj Var</em>'.
	 * @see org.eclipse.sme.frsl.ObjVar
	 * @generated
	 */
	EClass getObjVar();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.ObjVar#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.ObjVar#getName()
	 * @see #getObjVar()
	 * @generated
	 */
	EAttribute getObjVar_Name();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.ObjVar#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Type</em>'.
	 * @see org.eclipse.sme.frsl.ObjVar#getType()
	 * @see #getObjVar()
	 * @generated
	 */
	EReference getObjVar_Type();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.ObjVar#isIsMatched <em>Is Matched</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Is Matched</em>'.
	 * @see org.eclipse.sme.frsl.ObjVar#isIsMatched()
	 * @see #getObjVar()
	 * @generated
	 */
	EAttribute getObjVar_IsMatched();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.VarLink <em>Var Link</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Var Link</em>'.
	 * @see org.eclipse.sme.frsl.VarLink
	 * @generated
	 */
	EClass getVarLink();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.VarLink#getObjVar <em>Obj Var</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Obj Var</em>'.
	 * @see org.eclipse.sme.frsl.VarLink#getObjVar()
	 * @see #getVarLink()
	 * @generated
	 */
	EReference getVarLink_ObjVar();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.VarLink#getAssoc <em>Assoc</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Assoc</em>'.
	 * @see org.eclipse.sme.frsl.VarLink#getAssoc()
	 * @see #getVarLink()
	 * @generated
	 */
	EReference getVarLink_Assoc();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.VarLink#isIsNeg <em>Is Neg</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Is Neg</em>'.
	 * @see org.eclipse.sme.frsl.VarLink#isIsNeg()
	 * @see #getVarLink()
	 * @generated
	 */
	EAttribute getVarLink_IsNeg();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.Actor <em>Actor</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Actor</em>'.
	 * @see org.eclipse.sme.frsl.Actor
	 * @generated
	 */
	EClass getActor();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Actor#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.eclipse.sme.frsl.Actor#getName()
	 * @see #getActor()
	 * @generated
	 */
	EAttribute getActor_Name();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Actor#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.Actor#getDescription()
	 * @see #getActor()
	 * @generated
	 */
	EAttribute getActor_Description();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.Action <em>Action</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Action</em>'.
	 * @see org.eclipse.sme.frsl.Action
	 * @generated
	 */
	EClass getAction();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Action#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Type</em>'.
	 * @see org.eclipse.sme.frsl.Action#getType()
	 * @see #getAction()
	 * @generated
	 */
	EAttribute getAction_Type();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.Action#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see org.eclipse.sme.frsl.Action#getDescription()
	 * @see #getAction()
	 * @generated
	 */
	EAttribute getAction_Description();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.Action#getActor <em>Actor</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Actor</em>'.
	 * @see org.eclipse.sme.frsl.Action#getActor()
	 * @see #getAction()
	 * @generated
	 */
	EReference getAction_Actor();

	/**
	 * Returns the meta object for the reference list '{@link org.eclipse.sme.frsl.Action#getObjVars <em>Obj Vars</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference list '<em>Obj Vars</em>'.
	 * @see org.eclipse.sme.frsl.Action#getObjVars()
	 * @see #getAction()
	 * @generated
	 */
	EReference getAction_ObjVars();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.ActorAction <em>Actor Action</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Actor Action</em>'.
	 * @see org.eclipse.sme.frsl.ActorAction
	 * @generated
	 */
	EClass getActorAction();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.SystemAction <em>System Action</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>System Action</em>'.
	 * @see org.eclipse.sme.frsl.SystemAction
	 * @generated
	 */
	EClass getSystemAction();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.RejoinStep <em>Rejoin Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Rejoin Step</em>'.
	 * @see org.eclipse.sme.frsl.RejoinStep
	 * @generated
	 */
	EClass getRejoinStep();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.RejoinStep#getRejoinTo <em>Rejoin To</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Rejoin To</em>'.
	 * @see org.eclipse.sme.frsl.RejoinStep#getRejoinTo()
	 * @see #getRejoinStep()
	 * @generated
	 */
	EReference getRejoinStep_RejoinTo();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.RejoinStep#getCondition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Condition</em>'.
	 * @see org.eclipse.sme.frsl.RejoinStep#getCondition()
	 * @see #getRejoinStep()
	 * @generated
	 */
	EReference getRejoinStep_Condition();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.UCStep <em>UC Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>UC Step</em>'.
	 * @see org.eclipse.sme.frsl.UCStep
	 * @generated
	 */
	EClass getUCStep();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.sme.frsl.UCStep#getIncludedUC <em>Included UC</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Included UC</em>'.
	 * @see org.eclipse.sme.frsl.UCStep#getIncludedUC()
	 * @see #getUCStep()
	 * @generated
	 */
	EReference getUCStep_IncludedUC();

	/**
	 * Returns the meta object for class '{@link org.eclipse.sme.frsl.ActStep <em>Act Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Act Step</em>'.
	 * @see org.eclipse.sme.frsl.ActStep
	 * @generated
	 */
	EClass getActStep();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.ActStep#getPreSnapshot <em>Pre Snapshot</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Pre Snapshot</em>'.
	 * @see org.eclipse.sme.frsl.ActStep#getPreSnapshot()
	 * @see #getActStep()
	 * @generated
	 */
	EReference getActStep_PreSnapshot();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.sme.frsl.ActStep#getPostSnapshot <em>Post Snapshot</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Post Snapshot</em>'.
	 * @see org.eclipse.sme.frsl.ActStep#getPostSnapshot()
	 * @see #getActStep()
	 * @generated
	 */
	EReference getActStep_PostSnapshot();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.sme.frsl.ActStep#getAction <em>Action</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Action</em>'.
	 * @see org.eclipse.sme.frsl.ActStep#getAction()
	 * @see #getActStep()
	 * @generated
	 */
	EReference getActStep_Action();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.sme.frsl.ActStep#isIsActorStep <em>Is Actor Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Is Actor Step</em>'.
	 * @see org.eclipse.sme.frsl.ActStep#isIsActorStep()
	 * @see #getActStep()
	 * @generated
	 */
	EAttribute getActStep_IsActorStep();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	FrslFactory getFrslFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.FrslModelImpl <em>Model</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.FrslModelImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getFrslModel()
		 * @generated
		 */
		EClass FRSL_MODEL = eINSTANCE.getFrslModel();

		/**
		 * The meta object literal for the '<em><b>Actor</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FRSL_MODEL__ACTOR = eINSTANCE.getFrslModel_Actor();

		/**
		 * The meta object literal for the '<em><b>Usecase</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FRSL_MODEL__USECASE = eINSTANCE.getFrslModel_Usecase();

		/**
		 * The meta object literal for the '<em><b>Uc Extend</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FRSL_MODEL__UC_EXTEND = eINSTANCE.getFrslModel_UcExtend();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.UsecaseImpl <em>Usecase</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.UsecaseImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUsecase()
		 * @generated
		 */
		EClass USECASE = eINSTANCE.getUsecase();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute USECASE__NAME = eINSTANCE.getUsecase_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute USECASE__DESCRIPTION = eINSTANCE.getUsecase_Description();

		/**
		 * The meta object literal for the '<em><b>Primary Actor</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__PRIMARY_ACTOR = eINSTANCE.getUsecase_PrimaryActor();

		/**
		 * The meta object literal for the '<em><b>Secondary Actor</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__SECONDARY_ACTOR = eINSTANCE.getUsecase_SecondaryActor();

		/**
		 * The meta object literal for the '<em><b>Precondition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__PRECONDITION = eINSTANCE.getUsecase_Precondition();

		/**
		 * The meta object literal for the '<em><b>Postcondition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__POSTCONDITION = eINSTANCE.getUsecase_Postcondition();

		/**
		 * The meta object literal for the '<em><b>First Step</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__FIRST_STEP = eINSTANCE.getUsecase_FirstStep();

		/**
		 * The meta object literal for the '<em><b>Ext Point</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__EXT_POINT = eINSTANCE.getUsecase_ExtPoint();

		/**
		 * The meta object literal for the '<em><b>Include</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE__INCLUDE = eINSTANCE.getUsecase_Include();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.UsecasePreconditionImpl <em>Usecase Precondition</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.UsecasePreconditionImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUsecasePrecondition()
		 * @generated
		 */
		EClass USECASE_PRECONDITION = eINSTANCE.getUsecasePrecondition();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute USECASE_PRECONDITION__DESCRIPTION = eINSTANCE.getUsecasePrecondition_Description();

		/**
		 * The meta object literal for the '<em><b>Snapshot</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE_PRECONDITION__SNAPSHOT = eINSTANCE.getUsecasePrecondition_Snapshot();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.UsecasePostconditionImpl <em>Usecase Postcondition</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.UsecasePostconditionImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUsecasePostcondition()
		 * @generated
		 */
		EClass USECASE_POSTCONDITION = eINSTANCE.getUsecasePostcondition();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute USECASE_POSTCONDITION__DESCRIPTION = eINSTANCE.getUsecasePostcondition_Description();

		/**
		 * The meta object literal for the '<em><b>Snapshot</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference USECASE_POSTCONDITION__SNAPSHOT = eINSTANCE.getUsecasePostcondition_Snapshot();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.StepImpl <em>Step</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.StepImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getStep()
		 * @generated
		 */
		EClass STEP = eINSTANCE.getStep();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute STEP__NAME = eINSTANCE.getStep_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute STEP__DESCRIPTION = eINSTANCE.getStep_Description();

		/**
		 * The meta object literal for the '<em><b>Pre Step</b></em>' container reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference STEP__PRE_STEP = eINSTANCE.getStep_PreStep();

		/**
		 * The meta object literal for the '<em><b>Next Step</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference STEP__NEXT_STEP = eINSTANCE.getStep_NextStep();

		/**
		 * The meta object literal for the '<em><b>Alt Flow</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference STEP__ALT_FLOW = eINSTANCE.getStep_AltFlow();

		/**
		 * The meta object literal for the '<em><b>Rejoin From</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference STEP__REJOIN_FROM = eINSTANCE.getStep_RejoinFrom();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.IncludeImpl <em>Include</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.IncludeImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getInclude()
		 * @generated
		 */
		EClass INCLUDE = eINSTANCE.getInclude();

		/**
		 * The meta object literal for the '<em><b>Including UC</b></em>' container reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INCLUDE__INCLUDING_UC = eINSTANCE.getInclude_IncludingUC();

		/**
		 * The meta object literal for the '<em><b>Addition</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INCLUDE__ADDITION = eINSTANCE.getInclude_Addition();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ExtendImpl <em>Extend</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ExtendImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getExtend()
		 * @generated
		 */
		EClass EXTEND = eINSTANCE.getExtend();

		/**
		 * The meta object literal for the '<em><b>Extended UC</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference EXTEND__EXTENDED_UC = eINSTANCE.getExtend_ExtendedUC();

		/**
		 * The meta object literal for the '<em><b>Extension</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference EXTEND__EXTENSION = eINSTANCE.getExtend_Extension();

		/**
		 * The meta object literal for the '<em><b>Ext Point</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference EXTEND__EXT_POINT = eINSTANCE.getExtend_ExtPoint();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ExtensionPointImpl <em>Extension Point</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ExtensionPointImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getExtensionPoint()
		 * @generated
		 */
		EClass EXTENSION_POINT = eINSTANCE.getExtensionPoint();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EXTENSION_POINT__NAME = eINSTANCE.getExtensionPoint_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EXTENSION_POINT__DESCRIPTION = eINSTANCE.getExtensionPoint_Description();

		/**
		 * The meta object literal for the '<em><b>Location</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference EXTENSION_POINT__LOCATION = eINSTANCE.getExtensionPoint_Location();

		/**
		 * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference EXTENSION_POINT__CONDITION = eINSTANCE.getExtensionPoint_Condition();

		/**
		 * The meta object literal for the '<em><b>Extend</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference EXTENSION_POINT__EXTEND = eINSTANCE.getExtensionPoint_Extend();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.AltFlowImpl <em>Alt Flow</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.AltFlowImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getAltFlow()
		 * @generated
		 */
		EClass ALT_FLOW = eINSTANCE.getAltFlow();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ALT_FLOW__NAME = eINSTANCE.getAltFlow_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ALT_FLOW__DESCRIPTION = eINSTANCE.getAltFlow_Description();

		/**
		 * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ALT_FLOW__CONDITION = eINSTANCE.getAltFlow_Condition();

		/**
		 * The meta object literal for the '<em><b>Base Step</b></em>' container reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ALT_FLOW__BASE_STEP = eINSTANCE.getAltFlow_BaseStep();

		/**
		 * The meta object literal for the '<em><b>Alt Step</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ALT_FLOW__ALT_STEP = eINSTANCE.getAltFlow_AltStep();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.SnapshotPatternImpl <em>Snapshot Pattern</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.SnapshotPatternImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getSnapshotPattern()
		 * @generated
		 */
		EClass SNAPSHOT_PATTERN = eINSTANCE.getSnapshotPattern();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SNAPSHOT_PATTERN__NAME = eINSTANCE.getSnapshotPattern_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SNAPSHOT_PATTERN__DESCRIPTION = eINSTANCE.getSnapshotPattern_Description();

		/**
		 * The meta object literal for the '<em><b>Object</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SNAPSHOT_PATTERN__OBJECT = eINSTANCE.getSnapshotPattern_Object();

		/**
		 * The meta object literal for the '<em><b>Link</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SNAPSHOT_PATTERN__LINK = eINSTANCE.getSnapshotPattern_Link();

		/**
		 * The meta object literal for the '<em><b>Constraint</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SNAPSHOT_PATTERN__CONSTRAINT = eINSTANCE.getSnapshotPattern_Constraint();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ObjVarImpl <em>Obj Var</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ObjVarImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getObjVar()
		 * @generated
		 */
		EClass OBJ_VAR = eINSTANCE.getObjVar();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute OBJ_VAR__NAME = eINSTANCE.getObjVar_Name();

		/**
		 * The meta object literal for the '<em><b>Type</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference OBJ_VAR__TYPE = eINSTANCE.getObjVar_Type();

		/**
		 * The meta object literal for the '<em><b>Is Matched</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute OBJ_VAR__IS_MATCHED = eINSTANCE.getObjVar_IsMatched();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.VarLinkImpl <em>Var Link</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.VarLinkImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getVarLink()
		 * @generated
		 */
		EClass VAR_LINK = eINSTANCE.getVarLink();

		/**
		 * The meta object literal for the '<em><b>Obj Var</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VAR_LINK__OBJ_VAR = eINSTANCE.getVarLink_ObjVar();

		/**
		 * The meta object literal for the '<em><b>Assoc</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VAR_LINK__ASSOC = eINSTANCE.getVarLink_Assoc();

		/**
		 * The meta object literal for the '<em><b>Is Neg</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute VAR_LINK__IS_NEG = eINSTANCE.getVarLink_IsNeg();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ActorImpl <em>Actor</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ActorImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getActor()
		 * @generated
		 */
		EClass ACTOR = eINSTANCE.getActor();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ACTOR__NAME = eINSTANCE.getActor_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ACTOR__DESCRIPTION = eINSTANCE.getActor_Description();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ActionImpl <em>Action</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ActionImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getAction()
		 * @generated
		 */
		EClass ACTION = eINSTANCE.getAction();

		/**
		 * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ACTION__TYPE = eINSTANCE.getAction_Type();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ACTION__DESCRIPTION = eINSTANCE.getAction_Description();

		/**
		 * The meta object literal for the '<em><b>Actor</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ACTION__ACTOR = eINSTANCE.getAction_Actor();

		/**
		 * The meta object literal for the '<em><b>Obj Vars</b></em>' reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ACTION__OBJ_VARS = eINSTANCE.getAction_ObjVars();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ActorActionImpl <em>Actor Action</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ActorActionImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getActorAction()
		 * @generated
		 */
		EClass ACTOR_ACTION = eINSTANCE.getActorAction();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.SystemActionImpl <em>System Action</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.SystemActionImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getSystemAction()
		 * @generated
		 */
		EClass SYSTEM_ACTION = eINSTANCE.getSystemAction();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.RejoinStepImpl <em>Rejoin Step</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.RejoinStepImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getRejoinStep()
		 * @generated
		 */
		EClass REJOIN_STEP = eINSTANCE.getRejoinStep();

		/**
		 * The meta object literal for the '<em><b>Rejoin To</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference REJOIN_STEP__REJOIN_TO = eINSTANCE.getRejoinStep_RejoinTo();

		/**
		 * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference REJOIN_STEP__CONDITION = eINSTANCE.getRejoinStep_Condition();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.UCStepImpl <em>UC Step</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.UCStepImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getUCStep()
		 * @generated
		 */
		EClass UC_STEP = eINSTANCE.getUCStep();

		/**
		 * The meta object literal for the '<em><b>Included UC</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference UC_STEP__INCLUDED_UC = eINSTANCE.getUCStep_IncludedUC();

		/**
		 * The meta object literal for the '{@link org.eclipse.sme.frsl.impl.ActStepImpl <em>Act Step</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.sme.frsl.impl.ActStepImpl
		 * @see org.eclipse.sme.frsl.impl.FrslPackageImpl#getActStep()
		 * @generated
		 */
		EClass ACT_STEP = eINSTANCE.getActStep();

		/**
		 * The meta object literal for the '<em><b>Pre Snapshot</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ACT_STEP__PRE_SNAPSHOT = eINSTANCE.getActStep_PreSnapshot();

		/**
		 * The meta object literal for the '<em><b>Post Snapshot</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ACT_STEP__POST_SNAPSHOT = eINSTANCE.getActStep_PostSnapshot();

		/**
		 * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ACT_STEP__ACTION = eINSTANCE.getActStep_Action();

		/**
		 * The meta object literal for the '<em><b>Is Actor Step</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ACT_STEP__IS_ACTOR_STEP = eINSTANCE.getActStep_IsActorStep();

	}

} //FrslPackage
