/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Include</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sme.frsl.Include#getIncludingUC <em>Including UC</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Include#getAddition <em>Addition</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getInclude()
 * @model
 * @generated
 */
public interface Include extends EObject {
	/**
	 * Returns the value of the '<em><b>Including UC</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.Usecase#getInclude <em>Include</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Including UC</em>' container reference.
	 * @see #setIncludingUC(Usecase)
	 * @see org.eclipse.sme.frsl.FrslPackage#getInclude_IncludingUC()
	 * @see org.eclipse.sme.frsl.Usecase#getInclude
	 * @model opposite="include" required="true" transient="false"
	 * @generated
	 */
	Usecase getIncludingUC();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Include#getIncludingUC <em>Including UC</em>}' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Including UC</em>' container reference.
	 * @see #getIncludingUC()
	 * @generated
	 */
	void setIncludingUC(Usecase value);

	/**
	 * Returns the value of the '<em><b>Addition</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Addition</em>' reference.
	 * @see #setAddition(Usecase)
	 * @see org.eclipse.sme.frsl.FrslPackage#getInclude_Addition()
	 * @model required="true"
	 * @generated
	 */
	Usecase getAddition();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Include#getAddition <em>Addition</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Addition</em>' reference.
	 * @see #getAddition()
	 * @generated
	 */
	void setAddition(Usecase value);

} // Include
