/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.ocl.pivot.Constraint;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Snapshot Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sme.frsl.SnapshotPattern#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.SnapshotPattern#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.SnapshotPattern#getObject <em>Object</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.SnapshotPattern#getLink <em>Link</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.SnapshotPattern#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getSnapshotPattern()
 * @model
 * @generated
 */
public interface SnapshotPattern extends EObject {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getSnapshotPattern_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.SnapshotPattern#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getSnapshotPattern_Description()
	 * @model
	 * @generated
	 */
	String getDescription();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.SnapshotPattern#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
	void setDescription(String value);

	/**
	 * Returns the value of the '<em><b>Object</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.ObjVar}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Object</em>' containment reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getSnapshotPattern_Object()
	 * @model containment="true"
	 * @generated
	 */
	EList<ObjVar> getObject();

	/**
	 * Returns the value of the '<em><b>Link</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.VarLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Link</em>' containment reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getSnapshotPattern_Link()
	 * @model containment="true"
	 * @generated
	 */
	EList<VarLink> getLink();

	/**
	 * Returns the value of the '<em><b>Constraint</b></em>' reference list.
	 * The list contents are of type {@link org.eclipse.ocl.pivot.Constraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Constraint</em>' reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getSnapshotPattern_Constraint()
	 * @model
	 * @generated
	 */
	EList<Constraint> getConstraint();

} // SnapshotPattern
