/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sme.frsl.Step#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Step#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Step#getPreStep <em>Pre Step</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Step#getNextStep <em>Next Step</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Step#getAltFlow <em>Alt Flow</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Step#getRejoinFrom <em>Rejoin From</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getStep()
 * @model
 * @generated
 */
public interface Step extends EObject {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getStep_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Step#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getStep_Description()
	 * @model
	 * @generated
	 */
	String getDescription();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Step#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
	void setDescription(String value);

	/**
	 * Returns the value of the '<em><b>Pre Step</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.Step#getNextStep <em>Next Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Pre Step</em>' container reference.
	 * @see #setPreStep(Step)
	 * @see org.eclipse.sme.frsl.FrslPackage#getStep_PreStep()
	 * @see org.eclipse.sme.frsl.Step#getNextStep
	 * @model opposite="nextStep" transient="false"
	 * @generated
	 */
	Step getPreStep();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Step#getPreStep <em>Pre Step</em>}' container reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Pre Step</em>' container reference.
	 * @see #getPreStep()
	 * @generated
	 */
	void setPreStep(Step value);

	/**
	 * Returns the value of the '<em><b>Next Step</b></em>' containment reference.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.Step#getPreStep <em>Pre Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Next Step</em>' containment reference.
	 * @see #setNextStep(Step)
	 * @see org.eclipse.sme.frsl.FrslPackage#getStep_NextStep()
	 * @see org.eclipse.sme.frsl.Step#getPreStep
	 * @model opposite="preStep" containment="true"
	 * @generated
	 */
	Step getNextStep();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Step#getNextStep <em>Next Step</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Next Step</em>' containment reference.
	 * @see #getNextStep()
	 * @generated
	 */
	void setNextStep(Step value);

	/**
	 * Returns the value of the '<em><b>Alt Flow</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.AltFlow}.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.AltFlow#getBaseStep <em>Base Step</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Alt Flow</em>' containment reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getStep_AltFlow()
	 * @see org.eclipse.sme.frsl.AltFlow#getBaseStep
	 * @model opposite="baseStep" containment="true"
	 * @generated
	 */
	EList<AltFlow> getAltFlow();

	/**
	 * Returns the value of the '<em><b>Rejoin From</b></em>' reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.RejoinStep}.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.RejoinStep#getRejoinTo <em>Rejoin To</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Rejoin From</em>' reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getStep_RejoinFrom()
	 * @see org.eclipse.sme.frsl.RejoinStep#getRejoinTo
	 * @model opposite="rejoinTo"
	 * @generated
	 */
	EList<RejoinStep> getRejoinFrom();

} // Step
