/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getSystemAction()
 * @model
 * @generated
 */
public interface SystemAction extends Action {
} // SystemAction
