/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Usecase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getPrimaryActor <em>Primary Actor</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getSecondaryActor <em>Secondary Actor</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getPrecondition <em>Precondition</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getPostcondition <em>Postcondition</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getFirstStep <em>First Step</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getExtPoint <em>Ext Point</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.Usecase#getInclude <em>Include</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase()
 * @model
 * @generated
 */
public interface Usecase extends EObject {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Usecase#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_Description()
	 * @model
	 * @generated
	 */
	String getDescription();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Usecase#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
	void setDescription(String value);

	/**
	 * Returns the value of the '<em><b>Primary Actor</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Primary Actor</em>' reference.
	 * @see #setPrimaryActor(Actor)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_PrimaryActor()
	 * @model
	 * @generated
	 */
	Actor getPrimaryActor();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Usecase#getPrimaryActor <em>Primary Actor</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Primary Actor</em>' reference.
	 * @see #getPrimaryActor()
	 * @generated
	 */
	void setPrimaryActor(Actor value);

	/**
	 * Returns the value of the '<em><b>Secondary Actor</b></em>' reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Secondary Actor</em>' reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_SecondaryActor()
	 * @model
	 * @generated
	 */
	EList<Actor> getSecondaryActor();

	/**
	 * Returns the value of the '<em><b>Precondition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Precondition</em>' containment reference.
	 * @see #setPrecondition(UsecasePrecondition)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_Precondition()
	 * @model containment="true"
	 * @generated
	 */
	UsecasePrecondition getPrecondition();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Usecase#getPrecondition <em>Precondition</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Precondition</em>' containment reference.
	 * @see #getPrecondition()
	 * @generated
	 */
	void setPrecondition(UsecasePrecondition value);

	/**
	 * Returns the value of the '<em><b>Postcondition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Postcondition</em>' containment reference.
	 * @see #setPostcondition(UsecasePostcondition)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_Postcondition()
	 * @model containment="true"
	 * @generated
	 */
	UsecasePostcondition getPostcondition();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Usecase#getPostcondition <em>Postcondition</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Postcondition</em>' containment reference.
	 * @see #getPostcondition()
	 * @generated
	 */
	void setPostcondition(UsecasePostcondition value);

	/**
	 * Returns the value of the '<em><b>First Step</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>First Step</em>' containment reference.
	 * @see #setFirstStep(Step)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_FirstStep()
	 * @model containment="true"
	 * @generated
	 */
	Step getFirstStep();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.Usecase#getFirstStep <em>First Step</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>First Step</em>' containment reference.
	 * @see #getFirstStep()
	 * @generated
	 */
	void setFirstStep(Step value);

	/**
	 * Returns the value of the '<em><b>Ext Point</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.ExtensionPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Ext Point</em>' containment reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_ExtPoint()
	 * @model containment="true"
	 * @generated
	 */
	EList<ExtensionPoint> getExtPoint();

	/**
	 * Returns the value of the '<em><b>Include</b></em>' containment reference list.
	 * The list contents are of type {@link org.eclipse.sme.frsl.Include}.
	 * It is bidirectional and its opposite is '{@link org.eclipse.sme.frsl.Include#getIncludingUC <em>Including UC</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Include</em>' containment reference list.
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecase_Include()
	 * @see org.eclipse.sme.frsl.Include#getIncludingUC
	 * @model opposite="includingUC" containment="true"
	 * @generated
	 */
	EList<Include> getInclude();

} // Usecase
