/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.sme.frsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Usecase Precondition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.sme.frsl.UsecasePrecondition#getDescription <em>Description</em>}</li>
 *   <li>{@link org.eclipse.sme.frsl.UsecasePrecondition#getSnapshot <em>Snapshot</em>}</li>
 * </ul>
 *
 * @see org.eclipse.sme.frsl.FrslPackage#getUsecasePrecondition()
 * @model
 * @generated
 */
public interface UsecasePrecondition extends EObject {
	/**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecasePrecondition_Description()
	 * @model
	 * @generated
	 */
	String getDescription();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.UsecasePrecondition#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
	void setDescription(String value);

	/**
	 * Returns the value of the '<em><b>Snapshot</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Snapshot</em>' containment reference.
	 * @see #setSnapshot(SnapshotPattern)
	 * @see org.eclipse.sme.frsl.FrslPackage#getUsecasePrecondition_Snapshot()
	 * @model containment="true"
	 * @generated
	 */
	SnapshotPattern getSnapshot();

	/**
	 * Sets the value of the '{@link org.eclipse.sme.frsl.UsecasePrecondition#getSnapshot <em>Snapshot</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Snapshot</em>' containment reference.
	 * @see #getSnapshot()
	 * @generated
	 */
	void setSnapshot(SnapshotPattern value);

} // UsecasePrecondition
