<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="frslcs" nsURI="http://www.xtext.org/sme/FRSLCS" nsPrefix="frslcs">
  <eClassifiers xsi:type="ecore:EClass" name="FrslModelCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//RootCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usecases" upperBound="-1"
        eType="#//UsecaseCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucExtends" upperBound="-1"
        eType="#//ExtendCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModel" eType="ecore:EClass ../../org.eclipse.ocl.xtext.oclinecore/model/OCLinEcoreCS.ecore#//TopLevelCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assocs" upperBound="-1"
        eType="#//AssociationCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//ActorCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsecaseCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryActor" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryActors" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="#//UsecasePreconditionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postcondition" eType="#//UsecasePostconditionCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstStep" eType="#//StepCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extPoints" upperBound="-1"
        eType="#//ExtensionPointCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsecasePreconditionCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshot" eType="#//SnapshotPatternCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsecasePostconditionCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshot" eType="#//SnapshotPatternCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStep" eType="#//StepCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="altFlows" upperBound="-1"
        eType="#//AltFlowCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedUC" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extPoints" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionPointCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//SnapshotPatternCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//ExtendCS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AltFlowCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//SnapshotPatternCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseStep" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="altStep" lowerBound="1"
        eType="#//StepCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnapshotPatternCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//ObjVarCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negObjects" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//VarLinkCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ConstraintCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjVarCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//TypedRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMatched" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarLinkCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objVars" lowerBound="2"
        upperBound="2" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assoc" lowerBound="1" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNeg" eType="ecore:EDataType ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assocEnds" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ReferenceCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrExpr" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpSpecificationCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objVars" upperBound="-1"
        eType="#//ObjVarCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpSpecificationCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorActionCS" eSuperTypes="#//ActionCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemActionCS" eSuperTypes="#//ActionCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="RejoinStepCS" eSuperTypes="#//StepCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//SnapshotPatternCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rejoinTo" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCStepCS" eSuperTypes="#//StepCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedUC" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ModelElementRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssocEndCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ReferenceCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActStepCS" eSuperTypes="#//StepCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preSnapshot" eType="#//SnapshotPatternCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postSnapshot" eType="#//SnapshotPatternCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ActionCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActorStep" eType="ecore:EDataType ../../org.eclipse.ocl.pivot/model/Pivot.ecore#T-pivot-Boolean"/>
  </eClassifiers>
</ecore:EPackage>
